[2022-06-13 08:07:49,990] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:07:46.200958+00:00 [queued]>
[2022-06-13 08:07:50,005] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:07:46.200958+00:00 [queued]>
[2022-06-13 08:07:50,006] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 08:07:50,006] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-13 08:07:50,007] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 08:07:50,034] {taskinstance.py:1377} INFO - Executing <Task(BigQueryToCloudStorageOperator): get_sources> on 2022-06-13 08:07:46.200958+00:00
[2022-06-13 08:07:50,041] {standard_task_runner.py:52} INFO - Started process 12760 to run task
[2022-06-13 08:07:50,047] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'a_call_dag', 'get_sources', 'manual__2022-06-13T08:07:46.200958+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/call_dag.py', '--cfg-path', '/tmp/tmp8upea7yq', '--error-file', '/tmp/tmp5xpvkle4']
[2022-06-13 08:07:50,049] {standard_task_runner.py:80} INFO - Job 15: Subtask get_sources
[2022-06-13 08:07:50,142] {task_command.py:370} INFO - Running <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:07:46.200958+00:00 [running]> on host 8ef6f3d8e77e
[2022-06-13 08:07:50,386] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_call_dag
AIRFLOW_CTX_TASK_ID=get_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T08:07:46.200958+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-13T08:07:46.200958+00:00
[2022-06-13 08:07:50,389] {bigquery_to_gcs.py:110} INFO - Executing extract of avid-ceiling-348503.wwxt202204.source_list into: gs://asia-east2-wwxt202204-97297697-bucket/data/source_list.json
[2022-06-13 08:07:50,391] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-06-13 08:07:50,392] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2022-06-13 08:07:50,395] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:1921: DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
  "This method is deprecated. Please use `BigQueryHook.insert_job` method.", DeprecationWarning

[2022-06-13 08:07:50,416] {bigquery.py:1538} INFO - Inserting job ***_1655107670415507_5639c3d75bae9d09fb9b3aa2396d2954
[2022-06-13 08:07:53,770] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/bigquery_to_gcs.py", line 128, in execute
    job = hook.get_job(job_id=job_id).to_api_repr()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1470, in get_job
    job = client.get_job(job_id=job_id, project=project_id, location=location)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 2073, in get_job
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/avid-ceiling-348503/jobs/airflow_1655107670415507_5639c3d75bae9d09fb9b3aa2396d2954?projection=full&prettyPrint=false: Not found: Job avid-ceiling-348503:airflow_1655107670415507_5639c3d75bae9d09fb9b3aa2396d2954
[2022-06-13 08:07:53,805] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=a_call_dag, task_id=get_sources, execution_date=20220613T080746, start_date=20220613T080749, end_date=20220613T080753
[2022-06-13 08:07:53,842] {standard_task_runner.py:97} ERROR - Failed to execute job 15 for task get_sources (404 GET https://bigquery.googleapis.com/bigquery/v2/projects/avid-ceiling-348503/jobs/airflow_1655107670415507_5639c3d75bae9d09fb9b3aa2396d2954?projection=full&prettyPrint=false: Not found: Job avid-ceiling-348503:airflow_1655107670415507_5639c3d75bae9d09fb9b3aa2396d2954; 12760)
[2022-06-13 08:07:53,897] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-13 08:07:54,379] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
