[2022-06-13 08:57:48,509] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:57:45.536963+00:00 [queued]>
[2022-06-13 08:57:48,522] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:57:45.536963+00:00 [queued]>
[2022-06-13 08:57:48,522] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 08:57:48,523] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-13 08:57:48,523] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 08:57:48,546] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_sources> on 2022-06-13 08:57:45.536963+00:00
[2022-06-13 08:57:48,553] {standard_task_runner.py:52} INFO - Started process 14894 to run task
[2022-06-13 08:57:48,556] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'a_call_dag', 'get_sources', 'manual__2022-06-13T08:57:45.536963+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/call_dag.py', '--cfg-path', '/tmp/tmp60x6ctq4', '--error-file', '/tmp/tmp_6xlu2i_']
[2022-06-13 08:57:48,558] {standard_task_runner.py:80} INFO - Job 29: Subtask get_sources
[2022-06-13 08:57:48,635] {task_command.py:370} INFO - Running <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:57:45.536963+00:00 [running]> on host 8ef6f3d8e77e
[2022-06-13 08:57:48,745] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_call_dag
AIRFLOW_CTX_TASK_ID=get_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T08:57:45.536963+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-13T08:57:45.536963+00:00
[2022-06-13 08:57:51,332] {python.py:173} INFO - Done. Returned value was: None
[2022-06-13 08:57:51,358] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=a_call_dag, task_id=get_sources, execution_date=20220613T085745, start_date=20220613T085748, end_date=20220613T085751
[2022-06-13 08:57:51,428] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-13 08:57:51,569] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
