[2022-06-13 08:48:38,988] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:48:36.354867+00:00 [queued]>
[2022-06-13 08:48:39,012] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:48:36.354867+00:00 [queued]>
[2022-06-13 08:48:39,013] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 08:48:39,013] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-06-13 08:48:39,015] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-13 08:48:39,071] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_sources> on 2022-06-13 08:48:36.354867+00:00
[2022-06-13 08:48:39,079] {standard_task_runner.py:52} INFO - Started process 14499 to run task
[2022-06-13 08:48:39,114] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'a_call_dag', 'get_sources', 'manual__2022-06-13T08:48:36.354867+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/call_dag.py', '--cfg-path', '/tmp/tmp32z0rinf', '--error-file', '/tmp/tmpwj1oiaeh']
[2022-06-13 08:48:39,120] {standard_task_runner.py:80} INFO - Job 27: Subtask get_sources
[2022-06-13 08:48:39,445] {task_command.py:370} INFO - Running <TaskInstance: a_call_dag.get_sources manual__2022-06-13T08:48:36.354867+00:00 [running]> on host 8ef6f3d8e77e
[2022-06-13 08:48:40,192] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=a_call_dag
AIRFLOW_CTX_TASK_ID=get_sources
AIRFLOW_CTX_EXECUTION_DATE=2022-06-13T08:48:36.354867+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-13T08:48:36.354867+00:00
[2022-06-13 08:48:42,105] {python.py:173} INFO - Done. Returned value was: None
[2022-06-13 08:48:42,135] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=a_call_dag, task_id=get_sources, execution_date=20220613T084836, start_date=20220613T084838, end_date=20220613T084842
[2022-06-13 08:48:42,249] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-13 08:48:42,372] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
